# run: conda env create --file environment.yml
name: attention_tsp
channels:
- pytorch
- conda-forge
- nvidia
dependencies:
- python>=3.8
- anaconda
- tqdm
- pytorch
- pytorch-cuda=11.7
- torchvision
- cuda91
- shapely
- pip
- pip:
  - tensorboard_logger
